shared:
  image: centos:centos7
  annotations:
    screwdriver.cd/executor: "sls"
jobs:
  setupk8s:
    requires: [~pr, ~commit]
    annotations:
      screwdriver.cd/executor: "k8s"
    steps:
      - installut: yum install -y yum-utils
      - addrepo: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
      - installtf: yum install -y terraform
      - verifytf: terraform –v
  setup:
    requires: [~pr, ~commit]
    steps:
      # yum update
      # yum -y install wget unzip
      # wget https://releases.hashicorp.com/terraform/0.12.2/terraform_0.12.2_linux_amd64.zip
      # unzip ./terraform_0.12.2_linux_amd64.zip –d /usr/local/bin
      - installtf: |
          yum install -y yum-utils
          yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
          yum install -y terraform
      - verifytf: terraform –v

  build:
    requires: [setup]
    steps:
      - setdir: cd lambda
      - install: npm install
      - zip: zip -r build.zip .

  deploy:
    requires: [build]
    steps:
      - setdir: cd deploy
      - init: terraform init
      - plan: terraform plan
      - deploy: terraform apply
      # - installcli: |
      #     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      #     unzip -q awscliv2.zip
      #     sudo ./aws/install
      # - verify: |
      #     which aws
      #     ls -l /usr/local/bin/aws
      #     aws --version
