shared:
  image: node:12
  annotations:
    screwdriver.cd/executor: "sls"
jobs:
  build:
    requires: [~pr, ~commit]
    steps:
      - setdir: cd lambda
      - install: npm install

  deploy:
    requires: [build]
    image: centos:centos7
    steps:
      - installtf: |
          yum install -y yum-utils 
          yum install -y zip unzip 
          yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
          yum install -y terraform
      - verifytf: terraform version
      - zippkg: cd lambda && zip -r build.zip .
      - setdir: cd ../deploy/
      - init: terraform init
      - plan: terraform plan
      - deploy: terraform apply
      # - installcli: |
      #     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      #     unzip -q awscliv2.zip
      #     sudo ./aws/install
      # - verify: |
      #     which aws
      #     ls -l /usr/local/bin/aws
      #     aws --version
