shared:
  image: centos:centos7
jobs:
  deployappsls:
    requires: [~pr, ~commit]
    annotations:
      screwdriver.cd/executor: "sls"
    environment:
      RESOURCE_REFIX: sd-aws-intg
      EXECUTOR: "Code Build"
      BG_COLOR: "powderblue"
    secrets:
      - PUBLIC_SUBNETS
      - SECURITY_GROUP_ID
    steps:
      - install-dep: |
          yum update -y
          yum install -y yum-utils 
          yum install -y zip unzip git curl gcc g++ make
          curl -sL https://rpm.nodesource.com/setup_12.x | bash -
          yum install -y nodejs npm
          yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
          yum install -y terraform
      - verify: |
          terraform version
          node -v
          npm -v
      - set-app-dir: cd lambda
      - install-app: npm install
      - pkg: zip -r build.zip .
      - copy: cp build.zip $SD_ARTIFACTS_DIR/
      - set-deploy-dir: cd ../deploy/
      - init: |
          echo "security_group_id=\"$SECURITY_GROUP_ID\"" > app.tfvars
          echo public_subnets=$PUBLIC_SUBNETS >> app.tfvars
          echo "resource_prefix=\"$RESOURCE_REFIX\"" >> app.tfvars
          echo "executor=\"$EXECUTOR\"" >> app.tfvars
          cat app.tfvars
          terraform init
      - plan: terraform plan -var-file=app.tfvars
      - deploy: terraform apply -auto-approve -var-file=app.tfvars
      # - installcli: |
      #     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      #     unzip -q awscliv2.zip
      #     sudo ./aws/install
      # - verify: |
      #     which aws
      #     ls -l /usr/local/bin/aws
      #     aws --version
  deployappeks:
    requires: [~pr, ~commit]
    annotations:
      screwdriver.cd/executor: "eks"
    environment:
      RESOURCE_REFIX: sd-eks-intg
      EXECUTOR: "Elastic Kubernetes Service"
      BG_COLOR: "powder-blue"
    secrets:
      - PUBLIC_SUBNETS
      - SECURITY_GROUP_ID
    steps:
      - install-dep: |
          yum update -y
          yum install -y yum-utils 
          yum install -y zip unzip git curl gcc g++ make
          curl -sL https://rpm.nodesource.com/setup_12.x | bash -
          yum install -y nodejs npm
          yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
          yum install -y terraform
      - verify: |
          terraform version
          node -v
          npm -v
      - set-app-dir: cd lambda
      - install-app: npm install
      - pkg: zip -r build.zip .
      - copy: cp build.zip $SD_ARTIFACTS_DIR/
      - set-deploy-dir: cd ../deploy/
      - init: |
          echo "security_group_id=\"$SECURITY_GROUP_ID\"" > app.tfvars
          echo public_subnets=$PUBLIC_SUBNETS >> app.tfvars
          echo "resource_prefix=\"$RESOURCE_REFIX\"" >> app.tfvars
          echo "executor=\"$EXECUTOR\"" >> app.tfvars
          cat app.tfvars
          terraform init
      - plan: terraform plan -var-file=app.tfvars
      - deploy: terraform apply -auto-approve -var-file=app.tfvars
