shared:
  image: centos:centos7
  annotations:
    screwdriver.cd/executor: "sls"
jobs:
  deployapp:
    requires: [~pr, ~commit]
    steps:
      - installtf: |
          yum update
          yum install -y yum-utils 
          yum install -y zip unzip git curl gcc g++ make
          curl -sL https://rpm.nodesource.com/setup_10.x | bash -
          yum install -y nodejs npm
          yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
          yum install -y terraform
      - verify: | 
          terraform version
          node –version
          npm –version
      - setdir1: cd lambda
      - installapp: npm install
      - pkg: zip -r build.zip .
      - copy: cp build.zip $SD_ARTIFACTS_DIR/
      - setdir2: cd ../deploy/
      - init: terraform init
      - plan: terraform plan
      - deploy: terraform apply -auto-approve
      # - installcli: |
      #     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      #     unzip -q awscliv2.zip
      #     sudo ./aws/install
      # - verify: |
      #     which aws
      #     ls -l /usr/local/bin/aws
      #     aws --version
